config/routes.rb
Testparkavi::Application.routes.draw do
  resources :centers

  resources :users

  resources :posts

end

app/models/center.rb
class Center < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  # GET /centers
  # GET /centers.json
  def index
    @centers = Center.all
 p 4444444444444444
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @centers }
    end
  end

  # GET /centers/1
  # GET /centers/1.json
  def show
    @center = Center.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @center }
    end
  end

  # GET /centers/new
  # GET /centers/new.json
  def new
    @center = Center.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @center }
    end
  end

  # GET /centers/1/edit
  def edit
    @center = Center.find(params[:id])
  end

  # POST /centers
  # POST /centers.json
  def create
    @center = Center.new(params[:center])

    respond_to do |format|
      if @center.save
        format.html { redirect_to @center, notice: 'Center was successfully created.' }
        format.json { render json: @center, status: :created, location: @center }
      else
        format.html { render action: "new" }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /centers/1
  # PUT /centers/1.json
  def update
    @center = Center.find(params[:id])

    respond_to do |format|
      if @center.update_attributes(params[:center])
        format.html { redirect_to @center, notice: 'Center was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centers/1
  # DELETE /centers/1.json
  def destroy
    @center = Center.find(params[:id])
    @center.destroy

    respond_to do |format|
      format.html { redirect_to centers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/_form.html.erb
<%= form_for(@center) do |f| %>
  <% if @center.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@center.errors.count, "error") %> prohibited this center from being saved:</h2>

      <ul>
      <% @center.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/centers/edit.html.erb
<h1>Editing center</h1>

<%= render 'form' %>

<%= link_to 'Show', @center %> |
<%= link_to 'Back', centers_path %>

app/views/centers/index.html.erb
<h1>Listing centers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @centers.each do |center| %>
  <tr>
    <td><%= center.name %></td>
    <td><%= link_to 'Show', center %></td>
    <td><%= link_to 'Edit', edit_center_path(center) %></td>
    <td><%= link_to 'Destroy', center, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Center', new_center_path %>

app/views/centers/new.html.erb
<h1>New center</h1>

<%= render 'form' %>

<%= link_to 'Back', centers_path %>

app/views/centers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @center.name %>
</p>


<%= link_to 'Edit', edit_center_path(@center) %> |
<%= link_to 'Back', centers_path %>